mio: do not reset in flight request count in close()
The ClientConnection::close() resets in_flight_response_count to zero,
which breaks the in flight request tracking logic. This may cause race
conditions:
1) ClientConnection::close() gets called, and in_flight_response_count
   sets to zero.
2) the client connection is destroyed with in flight request
3) a new connection is created, and reuse the just closed fd (token)
4) a reply for in flight request gets queued
5) the reply message will incorrectly dispatched to the new connection

Possible failure:
test server::tests::test_wait_in_flight_responses ... FAILED
test server::tests::test_wait_many_connections ... ok
test server::tests::test_wait_one_fd_connection ... ok
test server::tests::test_wait_one_connection ... ok
test server::tests::test_wait_parse_error ... ok

failures:

---- server::tests::test_wait_in_flight_responses stdout ----
thread 'server::tests::test_wait_in_flight_responses' panicked at 'called `Result::unwrap()` on an `Err` value: Underflow', src/server.rs:1124:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    server::tests::test_wait_in_flight_responses

Signed-off-by: Liu Jiang <gerry@linux.alibaba.com>